spring:
  application:
    name: sooatel-api

  datasource:
    url: ${JDBC_POSTGRES_URL}
    username: ${JDBC_POSTGRES_USERNAME}
    password: ${JDBC_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 220MB
      max-request-size: 220MB

server:
  port: 8086

jwt:
  signing-key: Biy3xH6+WY6asNSSngRdyHNnV+dSl0l62ZU1+9DLfESLVdquHelviFT0Gc1nDnu/yJDt9fA6pZRvcWb701gfc00dyDt9Ueb2ATTkqL+GNms=
  expiration-date: 7776000000
